"""Refresh YOUTUBE_COOKIES in .env from the persistent, already-logged-in
Chrome instance running on this machine (see .cookie_profile/).

Why this exists: cookies exported from a user's own browser and pasted into
this server's .env get revoked by Google as a "security rotation" within
hours, because they're suddenly used from a different network/IP than where
they were created. Running the logged-in session on THIS machine (same IP
that yt-dlp downloads from) avoids that mismatch entirely. This script pulls
the current cookie jar from that live session via the DevTools Protocol
(no export/paste needed) and writes it into .env in yt-dlp's expected
Netscape cookies.txt format.

One-time setup: a Chrome instance must be running on this host with
--remote-debugging-port=9223 and a persistent --user-data-dir, logged into
a Google account once via the noVNC bridge (see RUNBOOK.md). After that,
just re-run this script whenever cookies need refreshing — no browser
interaction required, as long as that Chrome process stays running and
logged in.
"""
import re
import sys
import time

CDP_URL = "http://localhost:9223"
ENV_PATH = "/teamspace/studios/this_studio/openshorts/.env"
COOKIES_FILE_PATH = "/teamspace/studios/this_studio/openshorts/cookies.txt"


def _netscape_line(cookie):
    domain = cookie["domain"]
    include_subdomains = "TRUE" if domain.startswith(".") else "FALSE"
    secure = "TRUE" if cookie.get("secure") else "FALSE"
    expires = int(cookie["expires"]) if cookie.get("expires", -1) and cookie["expires"] > 0 else 0
    return "\t".join([
        domain, include_subdomains, cookie.get("path", "/"), secure,
        str(expires), cookie["name"], cookie["value"],
    ])


# yt-dlp needs the whole Google SSO set to present an authenticated session.
# A jar carrying only YouTube's visitor/consent cookies reads to YouTube as a
# broken or spoofed login, which is treated MORE harshly than an anonymous
# request — that's the "Sign in to confirm you're not a bot" wall.
AUTH_COOKIES = {
    "SID", "HSID", "SSID", "APISID", "SAPISID",
    "__Secure-1PSID", "__Secure-1PAPISID", "__Secure-3PSID", "LOGIN_INFO",
}


def fetch_cookies():
    from playwright.sync_api import sync_playwright

    with sync_playwright() as p:
        browser = p.chromium.connect_over_cdp(CDP_URL)
        context = browser.contexts[0]
        page = context.pages[0] if context.pages else context.new_page()
        # "networkidle" never fires on YouTube — the page keeps long-lived
        # connections open, so this timed out every single run and the script
        # died before exporting anything, silently leaving .env pinned to
        # whatever stale (logged-out) cookies were last written. The navigation
        # is only a freshness nudge; the jar already lives in the profile, so a
        # failure here must not abort the export.
        try:
            page.goto("https://www.youtube.com", wait_until="domcontentloaded", timeout=20000)
            time.sleep(2)
        except Exception as e:  # noqa: BLE001 - navigation is best-effort
            print(f"⚠️  Navigation nudge failed ({type(e).__name__}); "
                  "exporting the profile's existing cookie jar anyway.", file=sys.stderr)

        # Pull EVERY domain, not just youtube.com URLs. The core SSO cookies
        # (SID/HSID/SSID/APISID/SAPISID/__Secure-1PSID/1PAPISID) are set on
        # .google.com; filtering by YouTube URLs dropped all of them, so even a
        # fully logged-in browser exported a half-session.
        cookies = [
            c for c in context.cookies()
            if any(d in c["domain"] for d in ("youtube.com", "google.com"))
        ]
        browser.close()
        return cookies


def write_env(cookies):
    lines = [
        "# Netscape HTTP Cookie File",
        "# https://curl.haxx.se/rfc/cookie_spec.html",
        "# Auto-generated by refresh_youtube_cookies.py — do not edit by hand.",
        "",
    ]
    for c in cookies:
        lines.append(_netscape_line(c))
    cookies_block = "\n".join(lines) + "\n"

    with open(ENV_PATH, "r") as f:
        env_content = f.read()

    new_var = f'YOUTUBE_COOKIES="{cookies_block}"'

    if "YOUTUBE_COOKIES=" in env_content:
        # Replace the existing (possibly multi-line, quoted) value.
        pattern = re.compile(r'YOUTUBE_COOKIES="[^"]*"', re.DOTALL)
        if pattern.search(env_content):
            env_content = pattern.sub(new_var, env_content, count=1)
        else:
            # Commented-out placeholder like `# YOUTUBE_COOKIES=...`
            env_content = re.sub(r'#?\s*YOUTUBE_COOKIES=.*', new_var, env_content, count=1)
    else:
        env_content = env_content.rstrip("\n") + "\n\n" + new_var + "\n"

    with open(ENV_PATH, "w") as f:
        f.write(env_content)

    # main.py reads /app/cookies.txt (the live jar) rather than the .env
    # value — the env was the legacy path and a stale env value used to
    # clobber the file at every job (round-5 live failure). Keep the file in
    # sync so the refresh loop stays the single source of truth for both.
    try:
        with open(COOKIES_FILE_PATH, "w") as f:
            f.write(cookies_block)
        print(f"   (also wrote {COOKIES_FILE_PATH})")
    except OSError as e:
        print(f"⚠️  Could not write {COOKIES_FILE_PATH}: {e}", file=sys.stderr)


def main():
    cookies = fetch_cookies()
    present = {c["name"] for c in cookies} & AUTH_COOKIES

    # Require a real session, not just "some auth-looking cookie". A jar with
    # only __Secure-3PSID (YouTube's third-party slot) but none of the
    # first-party SSO cookies is exactly the half-session that trips the bot
    # wall, and it used to pass the old any()-based check.
    core = {"SID", "__Secure-1PSID"} & present
    # LOGIN_INFO is required, not just "any identity cookie": the two bot-wall
    # regressions (3-aug-2026) were both jars missing exactly LOGIN_INFO while
    # carrying SAPISID/1PAPISID — the lax any-of check let a half-session
    # overwrite a good jar. Refuse to write a jar without it.
    if not (core and "LOGIN_INFO" in present):
        print("❌ No complete logged-in session on the persistent Chrome instance "
              f"(found: {sorted(present) or 'none'}). Refusing to overwrite the "
              "existing cookies with a half-session — log in via the noVNC "
              "bridge first (see RUNBOOK.md §6.4).", file=sys.stderr)
        sys.exit(1)

    write_env(cookies)
    print(f"✅ Wrote {len(cookies)} fresh cookies to {ENV_PATH} "
          f"(auth cookies: {len(present)}/{len(AUTH_COOKIES)} — {sorted(present)})")


if __name__ == "__main__":
    main()
